#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export GRASP_POSE_SOURCE=yolo
export SCENE_WIDE_NON_CUBE_RANKING=false
export DEBUG_NON_CUBE_ONLY=true
export EXECUTE_AFTER_SCENE_RANKING=true
export SCENE_RANK_MIN_POSE_Z="${SCENE_RANK_MIN_POSE_Z:-0.10}"
export SCENE_RANK_MIN_TOP_SCORE="${SCENE_RANK_MIN_TOP_SCORE:-0.0}"
export SCENE_PREOBSERVE_ENABLED="${SCENE_PREOBSERVE_ENABLED:-false}"
export NON_CUBE_BBOX_WIDTH_MARGIN="${NON_CUBE_BBOX_WIDTH_MARGIN:--0.18}"
export CUBE_NOMINAL_GRASP_WIDTH_M="${CUBE_NOMINAL_GRASP_WIDTH_M:-0.0178}"
export NON_CUBE_FIXED_WIDTH_MULTIPLIER="${NON_CUBE_FIXED_WIDTH_MULTIPLIER:-4.0}"
export SCALE_FILTER_CORNER_WORLD_Z="${SCALE_FILTER_CORNER_WORLD_Z:-0.275}"
export SCALE_FILTER_VOLUME_DOWN_M="${SCALE_FILTER_VOLUME_DOWN_M:-0.50}"
export SCALE_FILTER_CORNER_OUTPUT_FRAME="${SCALE_FILTER_CORNER_OUTPUT_FRAME:-base_link}"
export START_GRASP_SERVICE="${START_GRASP_SERVICE:-false}"

exec "$SCRIPT_DIR/run_hybrid_cleanup.sh" "$@"
